### ISSUE TITLE
Error: Unsupported operand types in /app/build/profiles/multisite_drupal_standard/themes/atomium/atomium/includes/registry.inc, line 144

### ISSUE THREAD

**Issue by fmmribeiro** [ec-europa/header_footer_corporate#14]
hello
I'm using 
php 5.6
platform.package.version = 2.5

I did a full rebuild  of my website
disabled my custom themes and now the default theme is Atomium 7.x-2.12

When I enable the header_footer_corporate module
It returns the following error

`
    9.7803  173293016  12. drush_pm_enable() phar:///usr/local/bin/drush/includes/command.inc:422
    9.7818  173384448  13. drush_module_enable() phar:///usr/local/bin/drush/commands/pm/pm.drush.inc:1181
    9.7819  173384928  14. module_enable() phar:///usr/local/bin/drush/commands/core/drupal/environment_7.inc:143
   10.5931  182121048  15. module_invoke() /app/build/includes/module.inc:505
   10.5931  182121408  16. call_user_func_array:{/app/build/includes/module.inc:934}() /app/build/includes/module.inc:934
   10.5931  182121840  17. header_footer_corporate_enable() /app/build/includes/module.inc:934
   10.7532  182175864  18. _breadcrumb__main_link() /app/build/sites/default/modules/custom/ec_europa/header_footer_corporate/header_footer_corporate.install:67
   10.7627  182236344  19. menu_link_load() /app/build/sites/default/modules/custom/ec_europa/header_footer_corporate/header_footer_corporate.install.inc:389
   10.7633  182255960  20. _menu_link_translate() /app/build/includes/menu.inc:2681
   10.7634  182258688  21. drupal_alter() /app/build/includes/menu.inc:950
   10.7634  182259176  22. menu_token_translated_menu_link_alter() /app/build/includes/module.inc:1171
   10.7634  182259288  23. token_get_info() /app/build/profiles/multisite_drupal_standard/modules/contrib/menu_token/menu_token.module:101
   10.7639  182260632  24. token_info() /app/build/profiles/multisite_drupal_standard/modules/contrib/token/token.module:517
   10.7639  182261016  25. module_invoke_all() /app/build/includes/token.inc:260
   10.9271  184347840  26. call_user_func_array:{/app/build/includes/module.inc:965}() /app/build/includes/module.inc:965
   10.9271  184348480  27. system_token_info() /app/build/includes/module.inc:965
   10.9276  184362032  28. l() /app/build/modules/system/system.tokens.inc:70
   10.9276  184362744  29. theme_get_registry() /app/build/includes/common.inc:2590
   10.9276  184364192  30. call_user_func_array:{/app/build/includes/theme.inc:277}() /app/build/includes/theme.inc:277
   10.9276  184364968  31. _theme_load_registry() /app/build/includes/theme.inc:277
   10.9276  184365480  32. ThemeRegistry->__construct() /app/build/includes/theme.inc:335
   10.9280  184365792  33. ThemeRegistry->initializeRegistry() /app/build/includes/theme.inc:395
   10.9280  184365792  34. theme_get_registry() /app/build/includes/theme.inc:411
   10.9280  184365936  35. call_user_func_array:{/app/build/includes/theme.inc:277}() /app/build/includes/theme.inc:277
   10.9280  184366488  36. _theme_load_registry() /app/build/includes/theme.inc:277
   10.9283  184366872  37. _theme_build_registry() /app/build/includes/theme.inc:325
   11.6603  198963976  38. drupal_alter() /app/build/includes/theme.inc:716
   11.6639  198998136  39. atomium_theme_registry_alter() /app/build/includes/module.inc:1171
   11.7378  199313192  40. _theme_post_process_registry() /app/build/profiles/multisite_drupal_standard/themes/atomium/atomium/includes/registry.inc:82

Drush command terminated abnormally due to an unrecoverable error.                                                                           [error]
Error: Unsupported operand types in /app/build/profiles/multisite_drupal_standard/themes/atomium/atomium/includes/registry.inc, line 144
`

The error  is triggered when 
$original_hook as the value "menu_items_ec_corporate"

**Comment by julien-** [comment]
Dear @fmmribeiro,
Please test the `issues/14` branch and send your feedback here.

If it is OK for you, a new release v2.0 will be deployed
Thank you.
