### ISSUE TITLE
breadcrumb ECL compliant?

### ISSUE THREAD

**Issue by steeff** [ec-europa/header_footer_corporate#2]
Following the ecl breadcrumb https://ec-europa.github.io/europa-component-library/ec/components/detail/ec-component-breadcrumb the font should be smaller on small devices and also adds 3 dots instead of the full labels as we have here https://webgate.acceptance.ec.europa.eu/multisite/growth/industry/sustainability_en

**Comment by steeff** [comment]
we also have an issue with the latest segment that should not be clickable. This has been fixed on the PR https://github.com/ec-europa/europa-component-library/pull/701
on your side how do you follow the ECL updates?

**Comment by julien-** [comment]
I don't follow the EC library updates, sorry.

It will indeed be better to include the latest components and not have an static version in _asssets/europa_ folder.

**Comment by julien-** [comment]
@steeff The last releases (v1.08 and v1.09) answer to your need. If it is OK for you, you can Close this issue. Thank you
