### ISSUE TITLE
Notices on some admin pages

### ISSUE THREAD

**Issue by steeff** [ec-europa/header_footer_corporate#7]
Notice: Undefined variable: header__ec_corporate in include() (line 100 of /home/ec2-user/environment/ener/lib/themes/energy/templates/page.tpl.php).
Notice: Undefined variable: footer__ec_corporate in include() (line 238 of /home/ec2-user/environment/ener/lib/themes/energy/templates/page.tpl.php).

are displayed in some admin pages like admin/structure/block when you click "configure" block. en easy fix would be to initialize the variables.

**Comment by julien-** [comment]
@steeff : Just in case if you need it one day, here is what I do in a project :

```
/**
 * Implements hook_enable().
 */
function MY_MODULE_enable() {
  // Admin Block admin pages with the admin theme.
  $admin_pages = variable_get('cce_basic_config_admin_pages', array());

  foreach ($admin_pages as $key => $value) {
    if (strpos($value, 'admin/structure/block') !== FALSE) {
      unset($admin_pages[$key]);
    }
  }

  variable_set('cce_basic_config_admin_pages', $admin_pages);
}
```
